# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bcad9c2e800b9dfa35e9c490b3375f30120f9597823ef5986f6233d8fcea7989d97cc6f7e3ee49b16a3afb962c7cc840727b5ed503a616227b8ebd365c053015

test:
  secret_key_base: 8239290e93fa5fd1ee2e7c0c7a7820f6cd2ca160cf91a78ebbaa49a57edee450782f4507e2a8bd919351ed73720c7e45bbb522f597e7ef7fe856faddbaa44ec4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
